language: node_js
node_js: node
deploy:
  provider: heroku
  api_key: 
    secure: vKqgQWKs1HHOoaWn5uez8F5kYnabhmc/6tl/M1BhtYjBxUsbEODIMWTziTbUMUrppoCVihWDzpdI133N9Tu6zgQNrpu3RYhdfZzJE86gp/nb3dnDd+X4bBw72LX2n2xj1tffeeKG61xbVloD664D8686P+fR5uuyfYb7SIbf7t0Eu3137RSm+8GyCxUtlznP/LjLy1k192QIwcf2Qh+1/l1of9vbkLQb/3iuOZC6CJ02Izf8RRoLNJ4gf19+TPpc20egb+258hJ/1QIbnsDUsjgr6Ac5ekywpt7J0/SHDF3VikvaFZh/reUyn1PicV1WqUsVLroJCizh6I6ANrACdOujvYtDqvAbM7WOFRUFSTwo/kmYf+fF64oJCVDsu2/TelNex6jIuM/q7OOp1GScDIJzkEbFmdA9oy2l+j/9ptszKrSZ0ezq/utUIwt1tOtPgfib9z5svq0OB4+N+n/6bGYkUEZREbOZ+19Re4UqnuyNlDoPK8RaNJXjLrXyoe0lc70mQYPKpX08AgysXrsykAw02Gq8D2GIdblon9fvdUVWNtHfAPfREkYlutoqTTX8HWOzUF0SMzJqADV0bMSQKYGtaEr8q7qZ5lKQTLcjMDkSVusFOZfrWYxN8XCrxw1lIHE9AqN743uSa7DxeLSslvkengVbgLLykv3FSvTnDl0=
  app: serene-savannah-68358